/*
 * Student ID :1690701550
 * Name       :Sirasak Tumtong
 * Section    :129B
 * No.        :
 * Course     : GI113 Computer Programming (GI)
 */

string bossName = "Kirin";
char rank = 'S';
int level = 7;
int maxHp = 240;
int currentHp = 175;
float attackPower = 42.5f;
double critMultiplier = 1.75;
bool isBoss = true;
Console.WriteLine("===== BOSS STATUS:INITIAL =====");
Console.WriteLine($"Name: {bossName}");
Console.WriteLine($"Rank: {rank}");
Console.WriteLine($"Level: {level}");
Console.WriteLine($"HP: {maxHp}");
Console.WriteLine($"Attack Power: {attackPower}");
Console.WriteLine($"Crit Multiplier: {critMultiplier}");
Console.WriteLine($"Is Boss: {isBoss}");
Console.WriteLine();
int hpPercent = currentHp * 100 / maxHp;
Console.WriteLine($"HP Percent: {hpPercent}%");
Console.WriteLine();
Console.WriteLine("Kirin takes 60 damage!");
currentHp = currentHp - 60;
Console.WriteLine();
Console.WriteLine("===== BOSS STATUS: AFTER DAMAGE =====");
Console.WriteLine($"HP: {currentHp}/{maxHp}");
hpPercent = currentHp * 100 / maxHp;
Console.WriteLine($"HP Percent: {hpPercent}%");
string Character1 = "Nicole";
char rarityChar1 = 'S';
int levelChar1 = 10;
int maxHpChar1 = 200;
int currentHpChar1 = 175;
float attackPowerChar1 = 47.5f;
bool isChar1 = true;
Console.WriteLine();
Console.WriteLine("===== CHARACTER STATUS:INITIAL =====");
Console.WriteLine($"Name: {Character1}");
Console.WriteLine($"Rarity: {rarityChar1}");
Console.WriteLine($"Level: {levelChar1}");
Console.WriteLine($"MAX HP: {maxHpChar1}");
Console.WriteLine($"CURRENT HP: {currentHpChar1}");
Console.WriteLine($"Attack Power: {attackPowerChar1}");
Console.WriteLine($"Is Char: {isChar1}");
string Character2 = "Billy";
char rarityChar2 = 'A';
int levelChar2 = 5;
int maxHpChar2 = 175;
int currentHpChar2 = 175;
double attackPowerChar2 = 42.5;
bool isChar2 = true;
Console.WriteLine();
Console.WriteLine("===== CHARACTER STATUS:INITIAL =====");
Console.WriteLine($"Name: {Character2}");
Console.WriteLine($"Rarity: {rarityChar2}");
Console.WriteLine($"Level: {levelChar2}");
Console.WriteLine($"HP: {maxHpChar2}");
Console.WriteLine($"HP: {currentHpChar2}");
Console.WriteLine($"Attack Power: {attackPowerChar2}");
Console.WriteLine($"Is Char: {isChar2}");
string Character3 = "Anby";
char rarityChar3 = 'A';
int levelChar3 = 20;
int maxHpChar3 = 500;
int currentHpChar3 = 250;
float attackPowerChar3 = 55.5f;
bool isChar3 = true;
Console.WriteLine();
Console.WriteLine("===== CHARACTER STATUS:INITIAL =====");
Console.WriteLine($"Name: {Character3}");
Console.WriteLine($"Rarity: {rarityChar3}");
Console.WriteLine($"Level: {levelChar3}");
Console.WriteLine($"HP: {maxHpChar3}");
Console.WriteLine($"HP: {currentHpChar3}");
Console.WriteLine($"Attack Power: {attackPowerChar3}");
Console.WriteLine($"Is Char: {isChar3}");
string Character4 = "Belle";
char rarityChar4 = 'S';
int levelChar4 = 15;
int maxHpChar4 = 1000;
int currentHpChar4 = 250;
double attackPowerChar4 = 37.5;
bool isChar4 = true;
Console.WriteLine();
Console.WriteLine("===== CHARACTER STATUS:INITIAL =====");
Console.WriteLine($"Name: {Character4}");
Console.WriteLine($"Rarity: {rarityChar4}");
Console.WriteLine($"Level: {levelChar4}");
Console.WriteLine($"HP: {maxHpChar4}");
Console.WriteLine($"HP: {currentHpChar4}");
Console.WriteLine($"Attack Power: {attackPowerChar4}");
Console.WriteLine($"Is Char: {isChar4}");